definitions:
  TaskPool.DeductRequest:
    properties:
      cost:
        type: number
      email_id:
        type: string
      euid:
        type: string
      subtitle:
        type: string
      video:
        type: string
    type: object
  TaskPool.TaskStatus:
    properties:
      error:
        example: There was an error
        type: string
      links:
        additionalProperties:
          additionalProperties:
            type: string
          type: object
        type: object
      processing_complete:
        example: false
        type: boolean
    type: object
  add_money.AddReqModel:
    properties:
      credits:
        example: 1000
        type: integer
      email:
        example: rajatn@gmail.com
        type: string
    type: object
  create_profile.CreateReqModel:
    properties:
      email:
        example: rajatn@gmail.com
        type: string
      initial_credits:
        description: default value
        example: 2100
        type: integer
      name:
        example: Rajat Kumar
        type: string
      phone:
        example: 8010201921
        type: integer
    type: object
  send_video.AudioRequest:
    properties:
      audio_length:
        example: 10
        type: number
      email:
        example: rajatn@gmail.com
        type: string
      file_link:
        example: https://www.emaple.com/file
        type: string
      language:
        description: 'TODO: Add support for dubbing multiple languages at the same
          time'
        example: hindi|telugu|marathi|bengali|tamil
        type: string
    required:
    - audio_length
    - email
    - file_link
    - language
    type: object
  send_video.Response:
    properties:
      euid:
        type: string
      msg:
        type: string
    type: object
host: localhost:9010
info:
  contact:
    email: support@vaaani.live
    name: API Support
    url: https://www.vaaani.live
  description: Testing Swagger APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://vaaani.live
  title: SocketBoys/Backned APIs
  version: "1.0"
paths:
  /audio/dub:
    post:
      consumes:
      - application/json
      description: Places a dub request on the machine, if the task is successfully
        created then you will get the uuid, that you can use to poll and get the task
        status
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/send_video.AudioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/send_video.Response'
      summary: Create Dub Request
      tags:
      - Create DubRequest
  /poll/:uuid:
    get:
      consumes:
      - application/json
      description: get the status of ongoing task request of processing the audio.
      parameters:
      - description: uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TaskPool.TaskStatus'
      summary: poll ongoing task status.
      tags:
      - Poll Get
  /profile/add_money:
    post:
      consumes:
      - application/json
      description: Adds a new transaction record to the transaction table, and you
        will get the final credits of user's account
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/add_money.AddReqModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Adds a new transaction record to the transaction table
      tags:
      - Create AddMoney
  /profile/create:
    post:
      consumes:
      - application/json
      description: Adds a new user where the primary key will be the gmail id and
        profile id will be given in response
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/create_profile.CreateReqModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: create a profile for the user using google auth
      tags:
      - Create Profile
  /profile/deduct_money:
    post:
      consumes:
      - application/json
      description: -ve credits are not yet handled
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/TaskPool.DeductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: deduct x amount of money from user's account
      tags:
      - Delete CutMoneyService
  /profile/txn_history:
    get:
      consumes:
      - application/json
      description: lazy loading can be added, to implement that pagination on BE will
        be required
      parameters:
      - description: rajatn@gmail.com
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: get a list of all the txns that the user did
      tags:
      - Get TxnHistory
schemes:
- http
swagger: "2.0"
